GET http://localhost:3000/
Host: localhost:3000
Accept: application/json

###


GET http://localhost:3000/patient
Host: localhost:3000
Accept: application/json


###

GET http://localhost:3000/doctor
Host: localhost:3000
Accept: application/json


###
GET http://localhost:3000/patient/6a0b52824eddb33bb8692810 HTTP/1.1
Host: localhost:3000
Accept: application/json

###
GET http://localhost:3000/doctor/6a0b52844eddb33bb869281d HTTP/1.1
Host: localhost:3000
Accept: application/json

###


POST http://localhost:3000/patient/create HTTP/1.1
Host: localhost:3000
Content-Type: application/json
Accept: application/json

{
    "firstName": "Joseph",
    "lastName": "New",
    "age": 50,
    "gender": "Female",
    "diagnosis": "Diabetes",
    "admissionDate": "2023-01-20",
    "status": "Outpatient",
    "doctor": "Dr. Mike"
}

###

POST http://localhost:3000/doctor/create HTTP/1.1
Content-Type: application/json

{
    "name": "Dr. Jonathan New",
    "specialty": "General Practice",
    "department": "Outpatient Clinic"
}

###

PUT http://localhost:3000/patient/update/6a0b52824eddb33bb8692810 HTTP/1.1
Content-Type: application/json

{

    "firstName": "Gergy",
    "lastName": "New",
    "age": 30,
    "gender": "Male",
    "diagnosis": "Flu",
    "admissionDate": "2023-01-15",
    "status": "Outpatient",
    "doctor": "Dr. Mike"
}
###

PUT http://localhost:3000/doctor/update/6a0b52844eddb33bb869281d HTTP/1.1
Content-Type: application/json

{
    "name": "Dr. Mike new",
    "specialty": "General Practice",
    "department": "Outpatient Clinic"
}

###

DELETE http://localhost:3000/patient/delete/6a0b52824eddb33bb8692810 HTTP/1.1
Host: localhost:3000
Accept: application/json

###

DELETE http://localhost:3000/doctor/delete/6a0c2ffdfcf5631041e245ef HTTP/1.1
Host: localhost:3000
Accept: application/json

