GET http://localhost:3000/
Host: localhost:3000
Accept: application/json

###

# @name login
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "email": "glade@yahoo.com",
    "password": "12345678"
}

###
@token = {{login.response.body.token}}

# @name getPatients
GET http://localhost:3000/patient HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name getPatient
GET http://localhost:3000/patient/629b6d8c4e9f7f8f7f8f7f8f HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name addPatient
POST http://localhost:3000/patient/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "firstName": "John",
    "lastName": "Doe",
    "age": 30,
    "gender": "Male",
    "diagnosis": "Diabetes",
    "admissionDate": "2022-01-01",
    "status": "Admitted",
    "doctor": "Dr. Smith"
}

###

# @name updatePatient
PUT http://localhost:3000/patient/update/6a16c7ca51232ad10cb17e90 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "firstName": "John",
    "lastName": "Doe",
    "age": 31,
    "gender": "Male",
    "diagnosis": "Diabetes",
    "admissionDate": "2022-01-01",
    "status": "Discharged",
    "doctor": "Dr. Smith"
}

###

# @name deletePatient
DELETE http://localhost:3000/patient/delete/6a16c7ca51232ad10cb17e90 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###
# @name getDoctors
GET http://localhost:3000/doctor HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name getDoctorbyId
GET http://localhost:3000/doctor/6a0b52844eddb33bb869281c HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name addDoctor
POST http://localhost:3000/doctor/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Dr. Smith",
    "specialty": "Cardiology",
    "department": "Cardiology"
}

###

# @name updateDoctor
PUT http://localhost:3000/doctor/update/629b6d8c4e9f7f8f7f8f7f8f HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Dr. Smith",
    "specialty": "Cardiology",
    "department": "Neurology"
}

###

# @name deleteDoctor
DELETE http://localhost:3000/doctor/delete/629b6d8c4e9f7f8f7f8f7f8f HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

